name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.0'

    - name: Install dependencies
      run: npm install
      working-directory: D:\Project\PAF_Assignment\paf-assignment-2024-jun_we_28\frontend\node_modules

    - name: Run tests
      run: npm test
